### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by joecool4476** [dg9vh/VarAC-Cloudlog-Uploader#1]
When I run the program, I get the following error:
Traceback (most recent call last):
line 4, in <module> import requests
ModuleNotFoundError: no module named 'requests'

Any idea how to fix that?

**Comment by dg9vh** [comment]
Depending on your environment you have to install pyhton3-requests with apt install python3-requests or you use pip install requests.

**Comment by joecool4476** [comment]
Thank you! Fixed that issue by installing requests. Now, I am getting a Key Error: 'api' any ideas on that one?

**Comment by dg9vh** [comment]
Did you modify the file https://github.com/dg9vh/VarAC-Cloudlog-Uploader/blob/main/varac_cloudlog_uploader.ini to your needs? Insert your API-Key there.

**Comment by joecool4476** [comment]
Yes, I did. I modified the url and the api.

**Comment by joecool4476** [comment]
The specific error says:
Traceback (most recent call last):
File "****main.py", line 41, in ><module>
json_string = {"key":config['DEFAULT']['api'], "station_profile_id":config['DEFAULT']['station_profile_id'], "type":"adif", "string";adif}
File "...configparser.py" line 1258 in ___getitem___
raise KeyError(key)
KeyError: 'api'

**Comment by dg9vh** [comment]
Could you paste your settings here with replaced API-Key by ***?
Do you have any spaces before or after = ?

**Comment by joecool4476** [comment]
[DEFAULT]
url=https://w8rjd.ddns.net/api/qso
api=***
station_profile_id=1

**Comment by dg9vh** [comment]
Change your URL to: https://w8rjd.ddns.net/index.php/api/qso - my example is working with mod_rewrite on Apache-side to remove the index.php. Your site does not use this... this is the first point i see...

**Comment by dg9vh** [comment]
Then: are you calling this script from the directory the files are hosted from command line? What OS you are using?

**Comment by joecool4476** [comment]
I am using windows. I am calling the script from the my VarAc directory.

**Comment by joecool4476** [comment]
I changed the url and the problem persists.

**Comment by joecool4476** [comment]
Ok. I see what needed to happen. When I changed the command prompt directory to the directory that the script is in, then ran the program. It worked. 
Thank you! That was the trick.

**Comment by dg9vh** [comment]
> I am using windows. I am calling the script from the my VarAc directory.

So you copied the files into this directory... ok... I am running it with following command within the directory where I have my files:
python3 main.py

It seems there is a problem for the main.py to find the varac_cloudlog_uploader.ini - this should also resist in the same directory.

**Comment by dg9vh** [comment]
> Ok. I see what needed to happen. When I changed the command prompt directory to the directory that the script is in, then ran the program. It worked.
> Thank you! That was the trick.

Yes, that's the point :-) I have it running with a cmd-file from desktop that cd into the right directory before running it :-)

Have fun!
